### ISSUE TITLE
Create folder errors

### ISSUE THREAD

**Issue by ramontayag** [funkyfuture/docker-rpi-syncthing#1]
Do you see errors like `Creating folder: mkdir /home/syncthing: permission denied`?

Not sure why it complains about that... everything looks like it should make `/syncthing` the home directory.

![raspberrypi___syncthing](https://cloud.githubusercontent.com/assets/25332/22850842/e8b2c37c-f04b-11e6-82c5-f6bb6a876bae.png)

**Comment by funkyfuture** [comment]
some information about your container setup would be useful.

this could be caused by the fact that i changed the syncthing process to run as another user, see 429016baa24db7598d41eaeb526fd9241b0d3ba8. unfortunately i didn't came up with an idea how to announce this. anyway, if this is the case, a one-time adjustment of ownership should solve it. or - not recommended - you set `UID` and `GID` to `0`.

**Comment by ramontayag** [comment]
@funkyfuture it's a completely new docker container, and I'm mounting some test folders. I'm using ansible to start it, but it looks almost identical to docker compose:

```yaml
---
- name: Run syncthing container
  docker_container:
    name: syncthing
    image: funkyfuture/rpi-syncthing:0.14.23
    ports:
      - "8384:8384"
    volumes:
      - /home/pi/syncthing-test/data:/syncthing/data
      - /home/pi/syncthing/config:/syncthing/config
    restart: yes
    restart_policy: always
    network_mode: host
    env:
      GUI_ADDRESS: "[::]:8384"
```

I fail to realize why it's trying to create folders in `/home/syncthing`, when it should be doing so in `/syncthing`.
